store:
    availabilities:
        - German
        - International
    default_locale: en_GB
    localizations:
        - de_DE
        - en_GB
    categories:
        - BackendBearbeitung
    type: extension
    icon: src/Resources/store/icon.png
    automatic_bugfix_version_compatibility: true
    description:
        de: |
            <p>Mit diesem Plugin erhalten Sie ein einfaches durchsuchbares Archiv für E-Mails, die aus Shopware versendet werden.<br />
            Die E-Mails sind über den Menüpfad erreichbar: Einstellungen/Erweiterungen/Main Archiv.</p>
            <p>Dieses Plugin wird von <a href="https://store.shopware.com/friends-of-shopware.html">@FriendsOfShopware</a>
            entwickelt.<br />
            Maintainer dieses Plugins ist: <a rel="noopener noreferrer" target="_blank" href="https://github.com/shyim">Soner Sayakci</a></p>
            <p>Bei Fragen / Fehlern bitte ein <a rel="noopener noreferrer" target="_blank" href="https://github.com/FriendsOfShopware/FroshPlatformMailArchive/issues/new">Github Issue</a> erstellen</p>
        en: |
            <p>With this plugin you get a simple searchable archive for emails that are sent from Shopware.<br />
            The e-mails can be found via the menu path Settings/Extensions/Main Archive.</p>
            <p>This plugin is part of <a href="https://store.shopware.com/en/friends-of-shopware.html">@FriendsOfShopware</a>.<br />
            Maintainer from the plugin is: <a rel="noopener noreferrer" target="_blank" href="https://github.com/shyim">Soner Sayakci</a></p>
            <p>For questions or bugs please create a <a rel="noopener noreferrer" target="_blank" href="https://github.com/FriendsOfShopware/FroshPlatformMailArchive/issues/new">Github Issue</a></p>
    installation_manual:
        de: ""
        en: ""
    tags:
        de:
            - mail
            - archive
        en:
            - mail
            - archive
    features:
        de:
          - Übersicht der versendenten E-Mails
          - Durchsuchbares Archiv
          - Erneutes versenden von E-Mails
          - Automatisches entfernen alter E-Mails
          - E-Mails, die nicht versendet werden konnten, werden markiert (ab 2.0.5)
        en:
          - Overview of sent emails
          - Searchable archive
          - Resend emails
          - Automatically remove old emails
          - Emails that could not be sent are marked as failed (from 2.0.5)
    images:
        - file: src/Resources/store/img-0.png
          activate:
            de: true
            en: true
          preview:
            de: true
            en: true
          priority: 0
        - file: src/Resources/store/img-1.png
          activate:
            de: true
            en: true
          preview:
            de: false
            en: false
          priority: 0
build:
    zip:
        assets:
            enabled: true
            enable_es_build_for_admin: true
            enable_es_build_for_storefront: true

changelog:
    enabled: true
