name: PackPlugin
on:
    push:
        branches:
            - 0.2
        tags:
            - '*'

env:
    PLUGIN_NAME: FroshPlatformMailArchive
    ACCOUNT_USER: ${{ secrets.ACCOUNT_USER }}
    ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}

jobs:
    pack:
        runs-on: ubuntu-latest
        container: ghcr.io/friendsofshopware/platform-plugin-dev:v6.3.4
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    path: ${{ env.PLUGIN_NAME }}

            -   name: Build & create zip
                run: |
                    cp -r "./${PLUGIN_NAME}" "/plugins/${PLUGIN_NAME}"
                    start-mysql
                    pack-plugin "${PLUGIN_NAME}"

            -   name: Validate Zip
                run: /opt/bin/plugin-uploader ext:validate $(pwd)/${PLUGIN_NAME}.zip

            -   name: Upload to store
                if: startsWith(github.ref, 'refs/tags/')
                run: /opt/bin/plugin-uploader ext:upload $(pwd)/${PLUGIN_NAME}.zip --createRelease
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
